apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - myapp-deployment-and-hpa.yaml
  - myapp-service-and-ingress.yaml
  - myapp-namespace.yaml

images:
  - name: docker.io/jamaldevsecops/myapp
    newTag: v1.1  # This tag will be automatically updated by Argo CD Image Updater
